package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-12-08T19:01:15.796+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TunnelServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TunnelServiceSoap {

    @WebResult(name = "sendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMS")
    @WebMethod(action = "http://tempuri.org/sendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSResponse")
    public long sendSMS(
        @WebParam(name = "header", targetNamespace = "http://tempuri.org/")
        org.tempuri.InfoHeader header,
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        java.lang.String sender,
        @WebParam(name = "smsContent", targetNamespace = "http://tempuri.org/")
        java.lang.String smsContent,
        @WebParam(name = "receiverList", targetNamespace = "http://tempuri.org/")
        java.lang.String receiverList,
        @WebParam(name = "productCode", targetNamespace = "http://tempuri.org/")
        java.lang.String productCode,
        @WebParam(name = "pseudoFlag", targetNamespace = "http://tempuri.org/")
        java.lang.String pseudoFlag
    );
}
