package org.tempuri;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-12-08T19:01:15.875+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TunnelServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface TunnelServiceHttpPost {
}
